spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
  cloud:
    gateway:
      routes:
        - id: "test-route"
          uri: "http://localhost:9999"
          predicates:
            - Path=/**
          filters:
             - RedissonRateLimiter=config
#            - name: RequestRateLimiter
#              args:
#                key-resolver: "#{@userKeyResolver}"
#                redis-rate-limiter.replenishRate: 10
#                redis-rate-limiter.burstCapacity: 20

server:
  port: 9998
